[package]
name = "minkraft"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
# bevy = "0.2.1"
bevy = { path = "../bevy" }
bevy_prototype_character_controller = { git = "https://github.com/superdump/bevy_prototype_character_controller", branch = "main", features = [ "use_rapier" ] }
bevy_rapier3d = { git = "https://github.com/superdump/bevy_rapier", branch = "predict-for-render", features = [ "parallel", "simd-stable" ] }
ilattice3 = { git = "https://github.com/bonsairobo/ilattice3", rev = "9586551f" }
ilattice3-mesh = { git = "https://github.com/bonsairobo/ilattice3-mesh", rev = "15101c65e" }
noise = "0.6.0"
tracing = { version = "0.1.21", optional = true }
tracing-flame = { version = "0.1.0", optional = true }
tracing-subscriber = { version = "0.2.13", optional = true }

[patch.crates-io]
bevy = { path = "../bevy" }

[features]
default = [ "trace" ]
profiler = [ "bevy/profiler" ]
trace = [ "tracing", "tracing-flame", "tracing-subscriber", "bevy/trace" ]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1
