[package]
name = "minkraft"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.2.0"
bevy_fly_camera = "0.4.0"
env_logger = "0.7.1"
log = "0.4.11"
noise = "0.6.0"

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1
