[package]
name = "bevy-book"
version = "0.1.0"
authors = ["Robert Swain <robert.swain@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.1.3"
bevy_fly_camera = "0.3.0"
env_logger = "0.7.1"
noise = "0.6.0"
